### ISSUE TITLE
Derivation needed for matrix norms on p.53

### ISSUE THREAD

**Issue by peepeetee** [inducer/numerics-notes#12]
The leap from p.52 to p.53 is not exactly clear. I got victor to write it out for me real quick and now it is making sense.

Consider adding the derivation of the 1 norm and the infinite norm to a new slide

**Comment by inducer** [comment]
Thanks for the suggestion! It is often (but I guess not this time?) a quiz problem to find the maximizing vector. Having the derivation would spoil that question. Plus it's easy to Google. So this one is a "no" from me.
