### ISSUE TITLE
p.82 matrices should be singular

### ISSUE THREAD

**Issue by peepeetee** [inducer/numerics-notes#15]
as titled

**Comment by inducer** [comment]
![grafik](https://github.com/user-attachments/assets/3fa4a616-252d-4f29-b857-e42f3a0ab7d1)

Could you confirm that what you're asking is that "non-invertible" should be changed to "singular"? If so, how come? IMO, they're both perfectly fine words for the same concept.

**Comment by peepeetee** [comment]
![image](https://github.com/user-attachments/assets/0012fa3d-bc67-467f-aec3-582bc3a84b80)
The word `matrices` should be replaced with `matrix`, it's singular form

**Comment by inducer** [comment]
D'oh. I clearly overthought this one. Thanks for the report.
